# Generated by Django 4.2 on 2023-06-27 09:57

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_homepage_church_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevents",
            name="event_banner",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="upcomingevents",
            name="event_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 28, 9, 57, 58, 389970, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
