# Generated by Django 4.2 on 2023-07-03 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_upcomingevents_event_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevents",
            name="event_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 4, 21, 51, 46, 242525, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
