# Generated by Django 4.2 on 2023-07-03 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_upcomingevents_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevents",
            name="event_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 4, 21, 59, 35, 943339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
