# Generated by Django 4.2 on 2023-07-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_date_of_birth_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/images"),
        ),
    ]
